### PR TITLE
Task 4

### PR DESCRIPTION
**Pull request by tarunbhartiya7**
Backend:
```
  Stock model in DynamoDB:
  {
    product_id: '7567ec4b-b10c-48c5-9345-fc73c48a80aa',
    count: 2
  }

  Product model in DynamoDB:
  {
    description: "5.4-inch (13.7 cm diagonal) Super Retina XDR display",
    id: "7567ec4b-b10c-48c5-9345-fc73c48a80aa",
    price: 2400,
    title: "Yphone 13 mini"
  }
```
Frontend:
URL: https://d1rxysx81o0hyh.cloudfront.net

Backend:
getProduct - https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products
getProductById - https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products/{productId}
createProduct - https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products

Task 4.1:
- Added two tables - stocks and products
- Added a script in backend repo to fill data by running script

Task 4.2:
- Updated `serverless.yml` file to create two tables in DynamoDB automatically
- Integrated `getProductsById` to return single product for manage product page

Task 4.3:
- Created `createProduct` API through serverless.yml

Additional Tasks:
- Return error 500 status code on any error
- Add `console.log` statements for each incoming requests and their arguments

### CODE REVIEW

**Comment by margarita-sh** [comment]
4.1-done +1
4.2: 0.5
Extend your serverless.yml file with data about your database table and pass it to lambda’s environment variables section. - YOU DIDN'T IMPLEMENT
Integrate the getProductsList lambda to return via GET /products request a list of products from the database (joined stocks and products tables).  YOU DIDN'T IMPLEMENT, YOU DIDN'T COMBINE TWO TABLES - (joined stocks and products tables).
Integrate the getProductsById lambda to return via GET /products/{productId} request a single product from the database. - YOU DIDN'T IMPLEMENT, Your response didn't return count of the product:

description: "5.4-inch (13.7 cm diagonal) Super Retina XDR display"
id: "7567ec4b-b10c-48c5-9345-fc73c48a80aa"
price: 2400
title: "Yphone 13 mini"

4.3 - I wasn't able to check since post return error in postman, If it works, could you help me to get response? - 0.5
+1 (All languages) - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
+1 (All languages) - All lambdas do console.log for each incoming requests and their arguments

score 4, but if you do not agree, I can discuss it with you

**Comment by tarunbhartiya7** [comment]
@margarita-sh Post is working just fine. 

POST https://kras7hnycg.execute-api.ap-south-1.amazonaws.com/dev/products
Content-Type: application/json

{
    "description": "6.5-inch (15.5 cm diagonal) Super Retina XDR display",
    "price": 3000,
    "title": "Yphone 15"
}

image

Can you please check again?

Also, I have implemented following review points:
- Extend your serverless.yml file with data about your database table and pass it to lambda’s environment variables section
- join product and stock tables for `getProductsList` and `getProductsById`

**Comment by margarita-sh** [comment]
your score after improvements - 7

**Comment by tarunbhartiya7** [comment]
@margarita-sh Thanks for providing the detailed review which gave me opportunity to make improvements. I appreciate it.

**Pull request merged**
